In [1]:
print("hello")

hello


In [4]:
a='10'
print(type(a))

<class 'str'>


In [7]:
gift_price = 5000

my_money = int(input("Enter the amount: "))

friend_money = int(input("Enter the amount: "))

total_amount = my_money + friend_money

if total_amount >= gift_price and (my_money > 0 or friend_money > 0):
    print("Can purchase the gift I want")
elif total_amount < gift_price and total_amount > 0:
    print("Can purchase some other gift")
else:
    print("Cannot purchase the gift I want")

Can purchase some other gift


In [9]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [1]:
correct_password = "1234"
max_attempts = 3

for attempt in range(max_attempts):
    password = input("Enter your ATM password: ")

    if password == correct_password:
        print("Password correct. Transaction completed.")
        break
    else:
        remaining_attempts = max_attempts - attempt - 1
        print("Wrong password.")

        if remaining_attempts > 0:
            print("Attempts remaining:", remaining_attempts)
        else:
            print("Maximum attempts reached.")
            print("Your card and account have been blocked.")
else:
    print("Please contact your bank.")


Wrong password.
Attempts remaining: 2
Wrong password.
Attempts remaining: 1
Wrong password.
Maximum attempts reached.
Your card and account have been blocked.
Please contact your bank.


In [7]:
def hello(name):
    print(f"Hello, {name}!")  

hello("Ranjan")

Hello, Ranjan!


In [24]:
def sports_name(sports="Cricket"):
    print("What do you want to play:", sports)
sports_name()
sports_name("Football")
sports_name("Basketball")
sports_name("Tennis")
sports_name("Swimming")



What do you want to play: Cricket
What do you want to play: Football
What do you want to play: Basketball
What do you want to play: Tennis
What do you want to play: Swimming


In [26]:
def add(a,b):
    return a + b,a-b,a*b,a/b  
add(10, 20)

(30, -10, 200, 0.5)

In [33]:
def student_details(name, age, location, department="CSE"):
    print("Name:", name, "Age:", age, "Department:", department, "Location:", location)

students = [
    ("Ranjan", 22, "Kundapura"),
    ("athmik", 21, "Udupi"),
    ("adithya", 23, "karkala"),
    ("ashish", 20, "Hebri"),
    ("Dikisith", 22, "Koteshwara"),
    ("aryan", 21, "Hemmady"),
    ("Suhas", 24, "Marvanthe"),
    ("Abhishekh", 20, "Saligrama"),
    ("Jatin", 23, "Bhatkal"),
    ("Harsha", 22, "Kodi")
]

for student in students:
    student_details(*student)

Name: Ranjan Age: 22 Department: CSE Location: Kundapura
Name: athmik Age: 21 Department: CSE Location: Udupi
Name: adithya Age: 23 Department: CSE Location: karkala
Name: ashish Age: 20 Department: CSE Location: Hebri
Name: Dikisith Age: 22 Department: CSE Location: Koteshwara
Name: aryan Age: 21 Department: CSE Location: Hemmady
Name: Suhas Age: 24 Department: CSE Location: Marvanthe
Name: Abhishekh Age: 20 Department: CSE Location: Saligrama
Name: Jatin Age: 23 Department: CSE Location: Bhatkal
Name: Harsha Age: 22 Department: CSE Location: Kodi


In [34]:
def Student(**kwargs):
        print(kwargs)
Student(name="Ranjan", age=22, location="Kundapura", department="CSE")

{'name': 'Ranjan', 'age': 22, 'location': 'Kundapura', 'department': 'CSE'}


In [51]:
def Student(*args):
    print("Student Details:", args)

Student("Ranjan","Athmik","ashish")

Student Details: ('Ranjan', 'Athmik', 'ashish')


In [1]:
import numpy as np
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
import numpy as np
np.zeros((2,4),dtype=int)
np.ones((2,4),dtype=int)
np.full((4,2),"Hello")

array([['Hello', 'Hello'],
       ['Hello', 'Hello'],
       ['Hello', 'Hello'],
       ['Hello', 'Hello']], dtype='<U5')

In [7]:
import numpy as np
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
import numpy as np
np.diag([10,20,30])

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [8]:
import numpy as np
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
import numpy as np
a = np.array([[1, 2],
              [3, 4]])
print(a.T)

[[1 3]
 [2 4]]


In [ ]:
import numpy as np
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
print(np.matmul(a,b))

[[19 22]
 [43 50]]


In [13]:
import numpy as np
a = np.array([[1, 2,3,4,5,6]])
print(a.reshape(3,2))


[[1 2]
 [3 4]
 [5 6]]


In [17]:
import numpy as np
a=np.linspace(1,10,2)
print(a)

[ 1. 10.]


In [16]:

import numpy as np
np.arange(1,10,2)


array([1, 3, 5, 7, 9])